[project]
name = "databasic"
version = "0.1.0"
description = "Database connection helper"
readme = "README.md"
authors = [
    { name = "ansipunk", email = "ansipunk@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
    "psycopg[binary,pool]>=3.3.6",
    "sqlalchemy>=2.1.1",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "ruff>=0.16.9",
    "ty>=0.0.84",
]

[tool.pytest]
addopts = [
    "--cov", "src",
    "--cov-report", "term-missing",
    "--cov-report", "html",
    "--cov-fail-under", "100",
]
testpaths = [
    "tests",
]
